'use strict';

// Mapeo de códigos de mapa (asq_*) a nombres bonitos (Halo 3 Legacy).
module.exports = {
    'asq_chill': 'Narrows',
    'asq_constru': 'Construct',
    'asq_guardia': 'Guardian',
    'asq_cyberdy': 'The Pit',
    'asq_warehou': 'Amplified',
    'asq_midship': 'Heretic',
    'asq_epitaph': 'Epitaph',
    'asq_high_ground': 'High Ground',
    'asq_isolation': 'Isolation',
    'asq_last_resort': 'Last Resort',
    'asq_sandtrap': 'Sandtrap',
    'asq_snowbound': 'Snowbound',
    'asq_the_pit': 'The Pit',
    'asq_valhalla': 'Valhalla',
    'asq_blackout': 'Blackout',
    'asq_ghost_town': 'Ghost Town',
    'asq_rat_nest': 'Rat\'s Nest',
    'asq_standoff': 'Standoff',
    'asq_avalanche': 'Avalanche',
    'asq_foundry': 'Foundry',
    'asq_boundless': 'Snowbound (Boundless)',
    'asq_glacier': 'Cold Storage',
    'asq_orbital': 'Orbital',
    'asq_assembly': 'Assembly',
    'asq_citadel': 'Citadel',
    'asq_heretic': 'Heretic',
    'asq_longshore': 'Longshore',
    'asq_sandbox': 'Sandbox',
    'asq_tundra': 'Avalanche',
    'asq_descent': 'Assembly',
};
